# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

my_range <- function(n1, n2) {
    .Call(`_msCCA_my_range`, n1, n2)
}

msCCA_proximal_rank1 <- function(beta, X, R, rho_tol, rho_maxit, eta, norm_type, l0norm, l1norm, cl, eta_ratio, l1proximal_tol, l1proximal_maxit, line_search, line_maxit, eta_low, eps, trace = TRUE, print_out = 50L) {
    .Call(`_msCCA_msCCA_proximal_rank1`, beta, X, R, rho_tol, rho_maxit, eta, norm_type, l0norm, l1norm, cl, eta_ratio, l1proximal_tol, l1proximal_maxit, line_search, line_maxit, eta_low, eps, trace, print_out)
}

